### PR TITLE
Make the border of the note match the border of the note input box.

### PR DESCRIPTION
**Pull request by eliveikis**
This was a design change request made by Bill Bulman, in line with the future direction of the Shotgun website.

It adds a grey highlight border around the note:
image

### CODE REVIEW

**Comment by eliveikis** [comment]
@thebeeland, @manneohrstrom  or @robblau  Please review.

**Comment by eliveikis** [comment]
@manneohrstrom  You mentioned this would affect all DCC's but since this was requested by Bill perhaps it is ok to push it to all DCC's.

**Comment by manneohrstrom** [comment]
@eliveikis sounds good to me - we just need to make sure we liaise with @mathurf to hit the right spectrum of DCCs in the QA!

**Comment by eliveikis** [comment]
@manneohrstrom I think this change will require some updates - we need to apply the styling change to other potential widgets in the activity stream, like the version card. Will revisit post-release.

**Comment by gomezll** [comment]
@eliveikis Which is the version card? Could you describe in the pic you pasted above? Or is it the 'Info' portion above the notes in your pic (not shown). I can add the style to the version card. Also, are there any other widgets that need their style changed? For reference I have attached an image of the website's notes page for a specific version that's available here: https://3d-review.shotgunstudio.com/page/media_center?type=Version&id=6269&project_id=68

sg_web_activity_stream

**Comment by gomezll** [comment]
Merged these changes in, if during QA it is deemed appropriate will revisit making similar changes to other widgets

**Pull request merged**
